language: julia
julia:
  - 0.7.0

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/SeismicJulia/SeisProcessing.jl.git"));Pkg.build(); Pkg.test("SeisReconstruction"; coverage=true)'
